name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest

      # Fail only on real syntax/runtime-level issues (E9,F63,F7,F82), not style nits
      - name: Lint (flake8 - critical rules only)
        run: |
          flake8 . --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check formatting (black)
        run: |
          black --check .

      # Don’t fail the build if tests aren’t set up yet
      - name: Run tests (non-blocking for now)
        run: |
          pytest || true
